### ISSUE TITLE
Update to the new Dropbox javascript api 1.1

### ISSUE THREAD

**Issue by GianlucaGuarini** [dmytroyarmak/Backbone.dropboxDatastore#12]
It does not work properly using the new Dropbox js api https://www.dropbox.com/static/api/dropbox-datastores-1.1-latest.js

**Comment by dmytroyarmak** [comment]
Thank you, I'll try to fix it ASAP

**Comment by dmytroyarmak** [comment]
I've update my example app to dropbox js api 1.1 and it works fine: https://github.com/dmytroyarmak/todomvc-backbone.dropboxDatastore

@GianlucaGuarini What exactly problems do you have?

**Comment by GianlucaGuarini** [comment]
I think the error is in my app. I think Backbone combined with Backbone.relational posts the wrong data to the Dropbox api. The data sent contain cyclic object values. The 2 versions of the Dropbox api throws different error but I think the problem is elsewhere. 
- API 1.1 error:
  ![screen shot 2014-07-19 at 12 51 40](https://cloud.githubusercontent.com/assets/879612/3634522/0aad1c44-0f34-11e4-97df-1d17db8389a7.png)
- API 1.0 error:
  ![screen shot 2014-07-19 at 12 54 10](https://cloud.githubusercontent.com/assets/879612/3634523/0dcb53a0-0f34-11e4-87b7-a196d75ef5b6.png)

My app is on github https://github.com/time2/time2.github.io/tree/dev and its public url is https://time2.github.io/#!/sync/dropbox

Steps to reproduce the issue:
1. create a new project 
2. create a new task
3. refresh the page
4. create a new project

BTW using the localStorage everithing works fine

**Comment by dmytroyarmak** [comment]
Yeah. The problem is in result of `toJSON` method of yours models. It containts circular objects and objects with functions. It is from backbone.relational or from yours code but it should returns plain JS object that will be stored.

So you can try to find why there are a lot of garbage in result of `toJSON` or overwrite it in yours models.

**Comment by GianlucaGuarini** [comment]
This is definitely not a Backbone.dropboxDatastore issue thanks for your support
