### ISSUE TITLE
Using listeners to automatically receive changes from other instances of your app

### ISSUE THREAD

**Issue by dmytroyarmak** [dmytroyarmak/Backbone.dropboxDatastore#5]
https://www.dropbox.com/developers/datastore/tutorial/js#listeners
https://www.dropbox.com/developers/datastore/docs/js#Dropbox.Datastore.RecordsChanged

**Comment by alltom** [comment]
:+1: :)

**Comment by dmytroyarmak** [comment]
Made in 0.5.0
