### ISSUE TITLE
Open data store by ID

### ISSUE THREAD

**Issue by alltom** [dmytroyarmak/Backbone.dropboxDatastore#7]
https://www.dropbox.com/developers/datastore/docs/js#Dropbox.Datastore.DatastoreManager.openDatastore

**Comment by dmytroyarmak** [comment]
Hi. What actually do you want to be realized? Make able to use specific datastore per each Backbone.Collection? Or for all?

**Comment by alltom** [comment]
Per Backbone.Collection. I don't think that would change much in your API; I have per-collection LocalStorage stores by creating them in the collection's `initialize()`:

```
this.localStorage = new Backbone.LocalStorage(storageKey);
```

The context is a client-side web app (all data stored in localStorage, for now, with Dropbox soon I hope :) where the user has multiple projects. There is no data shared between projects, so for simplicity of querying, instead of storing project IDs in each model, the models are stored in a Backbone.LocalStorage keyed with the project ID. So when I initialize a collection of a project's models, I give the collection a key with which to initialize its Backbone.LocalStorage that includes the project ID.

I think it makes sense to continue this pattern by partitioning project data into Dropbox datastores, hence this feature request. :+1:

**Comment by dmytroyarmak** [comment]
Actually you can use different table for each collection and store it in one datastore. But different datastores also make sence. 
So, I'll implement it soon.
I think the API will be:

```
this.dropboxDatastore = new Backbone.DropboxDatastore('tableId', {
  datastoreId: 'datastoreId'
});
```

Second argument options with property datastoreId will be optional and if will not passed, default datastore will be used. Also If Datastore with passed id doen't exists I will create new one.

**Comment by alltom** [comment]
That sounds great. :) I wish I could've come with a pull request, but I'm backed up at the moment.

**Comment by dmytroyarmak** [comment]
Done. It should works in v0.3.1.

**Comment by alltom** [comment]
Spectacular!
